version: "3.8"

services:
  postgres:
    container_name: postgres_devsu
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: customer_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  customer-ms:
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
